language: clojure
script: lein test
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
env:
  global:
  - secure: uydHgduFqK447cqVC00Rsc9+4uZ3+UN5WTAjlQVksSlAugCzGL6Tu/8EM+RQRV+unCT2jOu6kECBVmv22j1WYSgefsml6FE82Oj/hRZAYIqxwUN1AXYrtVyTyHvHYs5N05cf/nu0MMlQmUlSPnuH267PZcENtfUVbiwwpCbRl02N2YMmRBpIQYXo4szInW6VXlvFm+5ZcFMVLr6uqqR7MnS5aIDpMMAloJHNbRkbpzqANFBU93x7uvdNsRje5dei5fPzAU34KV4RXvz4id7sjuyeCyxqcycqV26qBetKcMGWX3mNpBNCDomi4KeMyTYedtb5W8Y9JkR+INqfxYj5JSjOQxaXusrBpXG6pA7UDxS1XYEtfuo5+lQ7Yk27q4puax/XF0iETcULaqTgxPPI0qDikQl9PlhgXmi1WY1DZlBaUmOwC/YEL6dgfyxJnasmIbW6W6cpLEE0OHsL4Fg/Vv8ULRnihtN3kl5zPRXGt2SamPYHmmTaXQoyMa11E3XIn0bCUVtXA4uxGOHyT2s8SSzoA/2+K+n5cfrhoWabwTZzFQHrz24vgsFMBNOIVozHCfm0qsh8qvZk8MB7MZcxt+7oorF/WNovMhesYUhEPoWZBkuIUFrD3vj/THPmnuyIBzSZIuSa4672AKBb1Ohnp2Kt3zGtJfDiWVb8oPuI8d0=
  - secure: lymIpknQQOEPfd6M/RPIN+k3Jd4HzbGHO3EQR6DZ5FAFp6oe5YWcYXfZr+so0j60MDIcZcgJUXomTdbIjEY9JGZ7moJGTy5ECzJmzbLnKb9HVlbR8Ie++WkIm1ajYq8tAKKfW80IMGdAJAelViEQTF8l6IcWt8cvsapGg17KFX+DACqvWg3AwoI/Od5XFqDdiA484OwOIEXC1gFPbTd6VjKozUYQBn+D9ax+pFUkKvbupO+Ps5a0FGQxCE+pO3B3JyOkS1QHeCw7wS8kj/5Ej5Mc9YtCainZQ+1Nl5vsdieyEuPyQrndW0csrYyxrG9vnwiHPFBhp10nEHIYHaN/bbotY2d5pHociflS7RHlQN6u7/YjzK35zFrSUDu7+Cf091v+3KI4cGJ+LPvv+hSQ5Yd5XgKPhe/lqsR30LvuArmNvP/RCxGtf+dYoN4TolImhW8JCPhSQwK7oi9uIqeH0cuYJQApLYrsZWARfFmBnmRwRmHfnFTfiOjsFswPIeLYDB74PKgoZT9eRFJ3sy5TNoYaffFybRgPJCV5pPaEU58Jp43uV9Q1MFPkf4dCKz3sXoIoiFfgn7y6oEUEiHn0vk81/YA9X6ftq5YCc2G5lHnizBoQR7DNk8JwWk46kgq2gEFIaHvBDDqQOllay9jBwLSizggBrSxJLgFFBoG6Dfs=
