language: clojure
script: lein test
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
  email: false 
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
